# Generated by Django 5.0.4 on 2024-04-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='linkedIn',
            field=models.URLField(null=True),
        ),
    ]
