# Generated by Django 5.0.4 on 2024-04-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
